# each Fusion scan point info
uint8    device_id
uint8    type
uint16   number
float32  start_angle
float32  end_angle
uint64   scan_start_time
uint64   scan_end_time
uint64   device_start_time
uint64   device_end_time
float32  scan_frequency     # Hz
float32  beam_tilt
uint32   scan_flags
float32  yaw_angle
float32  pitch_angle
float32  roll_angle
float32  offset_x
float32  offset_y
float32  offset_z
resolution  resolution1
resolution  resolution2
resolution  resolution3
resolution  resolution4
resolution  resolution5
resolution  resolution6
resolution  resolution7
resolution  resolution8